using System;
using System.Collections.Generic;

namespace PdfEngine.Vector.Fonts;

/// <summary>
/// Metric and character advance tables for the 14 Standard PDF Fonts.
/// </summary>
/// <remarks>
/// Latin fonts (Helvetica, Times, Courier families) carry per-glyph advance widths keyed by glyph
/// name, generated by <c>eng/vectorpdf/tools/Generate-Standard14Metrics.ps1</c> from the
/// metric-compatible Windows core fonts (Arial ≡ Helvetica, Times New Roman ≡ Times). They match the
/// Adobe Core14 AFM values for the Adobe Standard Latin character set. Oblique variants share the
/// upright widths, exactly as in the AFMs. Courier is 600 for every glyph.
/// Symbol widths are generated from the Windows Symbol font (metric compatible with Adobe Symbol) and
/// keyed by the built-in Symbol code. ZapfDingbats widths are an approximation (a constant 788 with
/// 278 for space), because no metric-compatible system font exists.
/// </remarks>
public static class Standard14Fonts
{
    private static readonly HashSet<string> StandardNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique",
        "Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic",
        "Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique",
        "Symbol", "ZapfDingbats"
    };

    private static readonly Dictionary<string, string> Aliases = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Arial"] = "Helvetica", ["ArialMT"] = "Helvetica",
        ["Arial,Bold"] = "Helvetica-Bold", ["Arial-BoldMT"] = "Helvetica-Bold", ["Arial-Bold"] = "Helvetica-Bold",
        ["Arial,Italic"] = "Helvetica-Oblique", ["Arial-ItalicMT"] = "Helvetica-Oblique", ["Arial-Italic"] = "Helvetica-Oblique",
        ["Arial,BoldItalic"] = "Helvetica-BoldOblique", ["Arial-BoldItalicMT"] = "Helvetica-BoldOblique",
        ["Helvetica,Bold"] = "Helvetica-Bold", ["Helvetica,Italic"] = "Helvetica-Oblique",
        ["Helvetica,BoldItalic"] = "Helvetica-BoldOblique", ["Helvetica-Italic"] = "Helvetica-Oblique",
        ["Helvetica-BoldItalic"] = "Helvetica-BoldOblique",
        ["Times"] = "Times-Roman", ["TimesNewRoman"] = "Times-Roman", ["TimesNewRomanPSMT"] = "Times-Roman",
        ["TimesNewRoman,Bold"] = "Times-Bold", ["TimesNewRomanPS-BoldMT"] = "Times-Bold",
        ["TimesNewRoman,Italic"] = "Times-Italic", ["TimesNewRomanPS-ItalicMT"] = "Times-Italic",
        ["TimesNewRoman,BoldItalic"] = "Times-BoldItalic", ["TimesNewRomanPS-BoldItalicMT"] = "Times-BoldItalic",
        ["CourierNew"] = "Courier", ["CourierNewPSMT"] = "Courier",
        ["CourierNew,Bold"] = "Courier-Bold", ["CourierNewPS-BoldMT"] = "Courier-Bold",
        ["CourierNew,Italic"] = "Courier-Oblique", ["CourierNewPS-ItalicMT"] = "Courier-Oblique",
        ["CourierNew,BoldItalic"] = "Courier-BoldOblique", ["CourierNewPS-BoldItalicMT"] = "Courier-BoldOblique",
        ["Courier,Bold"] = "Courier-Bold", ["Courier,Italic"] = "Courier-Oblique",
        ["Courier,BoldItalic"] = "Courier-BoldOblique",
    };

    private static readonly Lazy<Dictionary<string, int>> NameIndex = new(() =>
    {
        var map = new Dictionary<string, int>(StringComparer.Ordinal);
        for (int i = 0; i < Standard14Metrics.GlyphNames.Length; i++)
            map[Standard14Metrics.GlyphNames[i]] = i;
        return map;
    });

    public static bool IsStandardFont(string fontName)
    {
        return NormalizeName(fontName) != null;
    }

    public static string CleanFontName(string fontName)
    {
        // Strip subset prefix (e.g. "ABCDEF+Helvetica" -> "Helvetica")
        int plusIdx = fontName.IndexOf('+');
        if (plusIdx >= 0 && plusIdx < fontName.Length - 1)
        {
            return fontName.Substring(plusIdx + 1);
        }
        return fontName;
    }

    /// <summary>
    /// Returns the canonical Standard 14 name for a base font name (subset prefix stripped, common
    /// Windows aliases such as <c>Arial,Bold</c> resolved), or <see langword="null"/> when the font is
    /// not one of the standard 14.
    /// </summary>
    public static string? NormalizeName(string? baseFont)
    {
        if (string.IsNullOrEmpty(baseFont))
            return null;
        string clean = CleanFontName(baseFont);
        if (StandardNames.TryGetValue(clean, out string? canonical))
            return canonical;
        return Aliases.TryGetValue(clean, out string? alias) ? alias : null;
    }

    /// <summary>True for the Symbol and ZapfDingbats standard fonts (built-in symbolic encodings).</summary>
    public static bool IsSymbolicStandardFont(string? baseFont) =>
        NormalizeName(baseFont) is "Symbol" or "ZapfDingbats";

    /// <summary>
    /// Width of a character code interpreted through the font's built-in encoding
    /// (StandardEncoding for the Latin fonts).
    /// </summary>
    public static bool TryGetWidth(string baseFont, int charCode, out double width)
    {
        width = 0;
        string? name = NormalizeName(baseFont);
        if (name == null || charCode < 0 || charCode > 255)
            return false;

        string?[] encoding = name switch
        {
            "Symbol" => FontEncodings.Symbol,
            "ZapfDingbats" => FontEncodings.ZapfDingbats,
            _ => FontEncodings.Standard
        };
        string? glyph = encoding[charCode];
        return glyph != null && TryGetWidthByName(name, glyph, out width);
    }

    /// <summary>
    /// Advance width (1/1000 em) of the named glyph in a standard font. Returns false when the font
    /// is not a standard font or it has no such glyph.
    /// </summary>
    public static bool TryGetWidthByName(string baseFont, string glyphName, out double width)
    {
        width = 0;
        string? name = NormalizeName(baseFont);
        if (name == null || string.IsNullOrEmpty(glyphName))
            return false;

        if (name.StartsWith("Courier", StringComparison.Ordinal))
        {
            // Courier is monospaced: exactly 600 units for every glyph it has.
            if (!NameIndex.Value.ContainsKey(glyphName) && !GlyphList.IsKnown(glyphName))
                return false;
            width = 600;
            return true;
        }

        if (name == "Symbol")
        {
            int code = Array.IndexOf(FontEncodings.Symbol, glyphName);
            if (code < 0 || Standard14Metrics.SymbolByCode[code] < 0)
                return false;
            width = Standard14Metrics.SymbolByCode[code];
            return true;
        }

        if (name == "ZapfDingbats")
        {
            if (Array.IndexOf(FontEncodings.ZapfDingbats, glyphName) < 0 && !glyphName.StartsWith('a'))
                return false;
            width = glyphName == "space" ? 278 : 788;
            return true;
        }

        short[] table = name switch
        {
            "Helvetica" or "Helvetica-Oblique" => Standard14Metrics.Helvetica,
            "Helvetica-Bold" or "Helvetica-BoldOblique" => Standard14Metrics.HelveticaBold,
            "Times-Roman" => Standard14Metrics.TimesRoman,
            "Times-Bold" => Standard14Metrics.TimesBold,
            "Times-Italic" => Standard14Metrics.TimesItalic,
            "Times-BoldItalic" => Standard14Metrics.TimesBoldItalic,
            _ => Standard14Metrics.Helvetica
        };

        if (!NameIndex.Value.TryGetValue(glyphName, out int idx))
        {
            // Try the canonical AGL name for algorithmic forms (uni0041 -> A).
            string? unicode = GlyphList.ToUnicode(glyphName);
            if (unicode == null || !Standard14Metrics.UnicodeIndex.Value.TryGetValue(unicode, out idx))
                return false;
        }

        short w = table[idx];
        if (w < 0)
            return false;
        width = w;
        return true;
    }

    /// <summary>
    /// Names of the Adobe Standard Latin character set (union of the Standard, WinAnsi and MacRoman
    /// encodings plus Latin Extended-A). Consumed by the metric generator script via reflection.
    /// </summary>
    internal static string[] LatinCharsetNames()
    {
        var set = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var table in new[] { FontEncodings.Standard, FontEncodings.WinAnsi, FontEncodings.MacRoman })
        {
            foreach (string? n in table)
            {
                if (n != null)
                    set.Add(n);
            }
        }
        foreach (string n in GlyphList.TableNames)
        {
            string? u = GlyphList.ToUnicode(n);
            if (u is { Length: 1 } && u[0] >= 0x100 && u[0] <= 0x17F)
                set.Add(n);
        }
        return new List<string>(set).ToArray();
    }
}
