<#
.SYNOPSIS
  Regenerates src/PdfEngine.Vector/Fonts/Standard14Metrics.g.cs.

.DESCRIPTION
  Throwaway generator for the Standard 14 font advance-width tables. Widths are taken from the
  metric-compatible Windows core fonts (Arial = Helvetica, Times New Roman = Times, Symbol = Symbol)
  through System.Windows.Media.GlyphTypeface (PresentationCore): AdvanceWidth * 1000, rounded.
  These fonts were designed to be metric compatible with the Adobe Core14 fonts, so the result
  matches the Adobe AFM widths for the Adobe Standard Latin character set.

  The glyph-name list and name -> Unicode mapping are read (via reflection) from the built
  PdfEngine.Vector assembly, so build the solution first:
      dotnet build src/PdfEngine.Vector
      pwsh eng/vectorpdf/tools/Generate-Standard14Metrics.ps1

  Windows only. Requires PowerShell 7 on .NET 9+.
#>
[CmdletBinding()]
param(
    [string]$AssemblyPath,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..\..')
if (-not $AssemblyPath) {
    $AssemblyPath = Join-Path $repoRoot 'src\PdfEngine.Vector\bin\Debug\net9.0\PdfEngine.Vector.dll'
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot 'src\PdfEngine.Vector\Fonts\Standard14Metrics.g.cs'
}

Add-Type -AssemblyName PresentationCore
$asm = [System.Reflection.Assembly]::LoadFrom((Resolve-Path $AssemblyPath))
$flags = [System.Reflection.BindingFlags]'Static,NonPublic,Public'
$std14 = $asm.GetType('PdfEngine.Vector.Fonts.Standard14Fonts')
$glyphList = $asm.GetType('PdfEngine.Vector.Fonts.GlyphList')
$names = $std14.GetMethod('LatinCharsetNames', $flags).Invoke($null, @())
$toUnicode = $glyphList.GetMethod('ToUnicode', $flags)

function Get-Face([string]$file) {
    $uri = [Uri]::new((Join-Path $env:WINDIR "Fonts\$file"))
    return [System.Windows.Media.GlyphTypeface]::new($uri)
}

function Get-WidthsByName([string]$file) {
    $face = Get-Face $file
    $map = $face.CharacterToGlyphMap
    $result = foreach ($n in $names) {
        $u = $toUnicode.Invoke($null, @([string]$n))
        $w = -1
        if ($u -and $u.Length -eq 1) {
            $cp = [int][char]$u
            $gid = 0
            if ($map.TryGetValue($cp, [ref]$gid)) {
                $w = [int][Math]::Round($face.AdvanceWidths[$gid] * 1000, [MidpointRounding]::AwayFromZero)
            }
        }
        $w
    }
    return ,$result
}

function Format-ShortArray([string]$fieldName, $values) {
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("    internal static readonly short[] $fieldName =")
    [void]$sb.AppendLine('    {')
    for ($i = 0; $i -lt $values.Count; $i += 16) {
        $chunk = $values[$i..([Math]::Min($i + 15, $values.Count - 1))]
        [void]$sb.AppendLine('        ' + (($chunk | ForEach-Object { "$_," }) -join ' '))
    }
    [void]$sb.AppendLine('    };')
    return $sb.ToString()
}

$fonts = [ordered]@{
    Helvetica       = 'arial.ttf'
    HelveticaBold   = 'arialbd.ttf'
    TimesRoman      = 'times.ttf'
    TimesBold       = 'timesbd.ttf'
    TimesItalic     = 'timesi.ttf'
    TimesBoldItalic = 'timesbi.ttf'
}

$out = [System.Text.StringBuilder]::new()
[void]$out.AppendLine('// <auto-generated>')
[void]$out.AppendLine('// Generated by eng/vectorpdf/tools/Generate-Standard14Metrics.ps1 from the metric-compatible')
[void]$out.AppendLine('// Windows core fonts. Do not edit by hand. Values are advance widths in 1/1000 em; -1 = no glyph.')
[void]$out.AppendLine('// </auto-generated>')
[void]$out.AppendLine('namespace PdfEngine.Vector.Fonts;')
[void]$out.AppendLine('')
[void]$out.AppendLine('internal static partial class Standard14Metrics')
[void]$out.AppendLine('{')
[void]$out.AppendLine('    internal static readonly string[] GlyphNames =')
[void]$out.AppendLine('    {')
for ($i = 0; $i -lt $names.Count; $i += 8) {
    $chunk = $names[$i..([Math]::Min($i + 7, $names.Count - 1))]
    [void]$out.AppendLine('        ' + (($chunk | ForEach-Object { "`"$_`"," }) -join ' '))
}
[void]$out.AppendLine('    };')
foreach ($key in $fonts.Keys) {
    [void]$out.AppendLine('')
    [void]$out.Append((Format-ShortArray $key (Get-WidthsByName $fonts[$key])))
}

# Symbol: keyed by built-in code. WPF maps U+0020..U+00FF onto the symbol cmap (F020..F0FF).
$symFace = Get-Face 'symbol.ttf'
$symMap = $symFace.CharacterToGlyphMap
$symbolEncoding = $asm.GetType('PdfEngine.Vector.Fonts.FontEncodings').GetField('Symbol', $flags).GetValue($null)
$symWidths = for ($c = 0; $c -lt 256; $c++) {
    $w = -1
    $gid = 0
    if ($null -ne $symbolEncoding[$c] -and ($symMap.TryGetValue($c, [ref]$gid) -or $symMap.TryGetValue(0xF000 + $c, [ref]$gid))) {
        $w = [int][Math]::Round($symFace.AdvanceWidths[$gid] * 1000, [MidpointRounding]::AwayFromZero)
    }
    $w
}
[void]$out.AppendLine('')
[void]$out.Append((Format-ShortArray 'SymbolByCode' $symWidths))
[void]$out.AppendLine('}')

[System.IO.File]::WriteAllText($OutputPath, $out.ToString().Replace("`r`n", "`n").Replace("`n", "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $OutputPath ($($names.Count) glyph names)"
